services:
  web:
    image: odoo:17
    depends_on:
        - db
    ports:
      - 8069:8069
    volumes:
      - ./odoo/filestore/:/var/lib/odoo/filestore
      - ./odoo/sessions/:/var/lib/odoo/sessions
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    user: root
    command: --dev=all 
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data